### ISSUE TITLE
User mode contains Spaceship generation progressbar and no reset button

### ISSUE THREAD

**Issue by gallorob** [arayabrain/space-engineers-ai-spaceship-generator#32]
**Issue:**
The “spaceship generation progress” indicator is shown even when the user chooses not to participate in the study. Additionally, there is a header above it that says “Study progress”

**Suggested fix:** 
Hide the progress bar when not in the study, change the header to “Spaceship generation progress” and add a “Reset progress” button that will start the evolution anew.

**Comment by gallorob** [comment]
After denying the data collection request, the webapp switches to user mode, which has the below layout:

![image](https://user-images.githubusercontent.com/32876132/192913214-af17ab0b-3e17-4a0e-999f-41a11440d484.png)

I could not encounter the situation described in the issue.

**Comment by martinpoliak-goodai** [comment]
I think I understand now - once I click "yes", I am in the "study" mode even after I restart the application. Would it make sense to add a special "Exit study" button that would allow the user to exit the user study prematurely? Of course, there should be some modal warning window telling the user that it's not a good choice :-)

**Comment by gallorob** [comment]
To be more precise, closing and reopening the browser (or simply refreshing the page) is unexpected behavior, hence the message in the `Log` to not refresh the page. The reason for that is that the webapp does not leverage session data since it slows down responsiveness **a lot**. So when you refresh the page, you actually reload the page with the default layout after the first initialization. The proper way to switch mode would be, as you pointed out, to just restart the executable.

However, if you believe it would be better, I can:

- [ ] Improve behaviour on page reload
- [ ]  Add a button to switch to user mode from user study mode early (one-way)

Let me know if you want me to go through with these changes!

**Comment by gallorob** [comment]
Page reload improvement implemented in 34c26c54d16bc2fca896a01260462a86d9952977

All application properties are kept on reload. Reloading during a callback breaks the callback (ie: no results are displayed).

**Comment by gallorob** [comment]
Added button to switch from user study mode to user mode (one-way) in ca03ffc8c9e14a00fa43f8af6bbbc717adf22c79

**Comment by gallorob** [comment]
Current implementation:

![image](https://user-images.githubusercontent.com/32876132/193494887-775dce15-e84c-4d26-a16e-4a7075699b6e.png)
