### ISSUE TITLE
Avoiding PyTorch dependency

### ISSUE THREAD

**Issue by gallorob** [arayabrain/space-engineers-ai-spaceship-generator#35]
The executables (main app, comparator app) that will be distributed to the players will contain MKL and PyTorch dlls (and possibly Anaconda). However, it should be possible to have `estimators.py` use `numpy` instead of `torch`? Or keep the app performance while not relying on NNs.

**Comment by gallorob** [comment]
To not use PyTorch, set `use_torch` in the `LIBRARY` section of the `configs.ini` file(s).

PyTorch is now excluded from the required dependencies when installing the PCGSEPy library if the above flag is set in the `configs.ini` file at the same level of the `setup.py`.

For now it is set to `False` by default as there are no noticeable differences in performances and reduces the executables filesize drastically.

**Comment by martinpoliak-goodai** [comment]
Awesome, that's a huge improvement, Roberto 👍
