### ISSUE TITLE
Ship thrusters

### ISSUE THREAD

**Issue by gallorob** [arayabrain/space-engineers-ai-spaceship-generator#36]
Are there thrusters generated on all six sides of the ship? If not, it will not be able to accelerate in some directions.

**Comment by gallorob** [comment]
No, there is no control over how many or on which sides the thrusters are generated. However the spaceship is able to rotate on all axis, so it's not limited in movement.

**Comment by martinpoliak-goodai** [comment]
Actually, there is a limitation in movement - the ships that are currently generated cannot decelerate, they can only accelerate in the forward direction. Additing thrusters in a reverse direction is therefore necessary. Adding thrusters in the remaining 2 axes would be a great feature, because lateral movement is currently impossible (necessary for docking e.g.)

**Comment by martinpoliak-goodai** [comment]
I spoke with Erin today, he said that the thrusters in the remaining directions are really important, because otherwise the ship would also crash on planet surface. Could you please add them?

**Comment by gallorob** [comment]
I see. I'll discuss with Kai the best approach to this and will update then
It's unfortunate this issue didn't come up earlier, but I'm sure there can be a good solution.

**Comment by gallorob** [comment]
@martinpoliak-goodai is this what you had in mind?
![alt_rules](https://user-images.githubusercontent.com/32876132/193209796-90bbce45-2d46-4120-a7d0-0f51be29bc8a.gif)
**All** spaceships would have the two thrusters in the front alongside the cockpit (can add variation on which axes they are placed), and the four ring-placed thrusters on the end.
I'm not going to push the changes for now, let me know if this is ok and then I'll make a proper commit.

**Comment by martinpoliak-goodai** [comment]
This is great, Roberto, yes, that's exactly what I had in mind :-)

**Comment by martinpoliak-goodai** [comment]
Sorry for taking long to respond, for some reasons I was not getting notifications from this issue despite being involved in the discussion.

**Comment by gallorob** [comment]
Implemented in de429e858fc6f1e40feac874d55b59d6b26e6e5c

I had the same issue in the past, I'll tag you in the next issues to avoid it :)
@martinpoliak-goodai
