### ISSUE TITLE
Change "Log" position

### ISSUE THREAD

**Issue by gallorob** [arayabrain/space-engineers-ai-spaceship-generator#41]
Move "Log" textarea below the download button and ship properties, and to the lower right of the content preview.

**Comment by gallorob** [comment]
Implemented in 9cbde1d5a8725710d3aebf89f808d579b42b1a9d

**Comment by gallorob** [comment]
Temporarily reverted since the "Content Properties" now takes up roughly the same amount of vertical space as the "Selected Spaceship".

Awaiting feedback.

**Comment by martinpoliak-goodai** [comment]
Looks good, let's wait for Erin's feedback.

**Comment by gallorob** [comment]
Closed with 98b5dd3c70828e32f3fc8a1abf3c79c439c503e2
