### ISSUE TITLE
3D preview - labels + sphere size

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#58]
Tests of the newest 3D preview:
1) please increase the size of the balls to 4, it was better 
    (line 1854 of webapp.py: marker=dict(size=**4**, ... )
2) the node label popups are different in the standard preview (shows x,y,z) and voxel preview (shows "largeArmorBlock" etc.) - if possible, please make them the same according to the specification you reached with Erin.

**Comment by gallorob** [comment]
Updated in 81022302463286fc10f32abbef3a6ea2744e2669
