### ISSUE TITLE
Hint buttons - add padding

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#59]
Currently, the hint buttons are tightly sitting on the text and on top of the graphs:
![obrazek](https://user-images.githubusercontent.com/14159877/195809995-a4226fb0-e2d1-42a1-9b9e-be3b9ba0a8cd.png)

Could you please add a small padding so that there is a separation between the button and the text to the left of it and the graph beneath it?

**Comment by gallorob** [comment]
Added padding in 4098cee2b163c250cc097ce83432449b7afd3182

![image](https://user-images.githubusercontent.com/32876132/196066693-cd6ccf76-45f2-4790-b82f-e4816f4c8a4c.png)

**Comment by martinpoliak-goodai** [comment]
Thanks! I checked the buttons and they are nicely padded. The bottom one (Spaceship Controls) has one style missing, I added a hint to your commit (add `'align-items': 'center',`)

**Comment by gallorob** [comment]
@martinpoliak-goodai added in c7f4bc52f8d2f329925aab324babda06dfb2fa8e
