### ISSUE TITLE
Spaceship Controls hint button opens download help

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#60]
Spaceship Controls hint button opens download help (not "Spaceship Controls help" as one might expect"). 

Could you please move the hint button next to the "download blueprint" text, if this is not in contradiction to the design you agreed on with Erin?

**Comment by gallorob** [comment]
Yeah, Erin suggested moving the button next to the "Spaceship Controls" label with no changes to the contents of the modal, but that can be confusing for the user. I changed the modal title and added information about changing spaceship color as well in 
33ce84b4b1de840ba6c331533a803d8d94005d68 and 17ddd52296d3bb25fd9d09a90debe9bfd85898c3
