### ISSUE TITLE
Download failed after the end of experiment #1

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#63]
After end of experiment #1, I clicked "download selected ship and start new experiment" and after a while, the app crashed (nothing visible in the web GUI, but error messages appeared in the executable log). I'm attaching the log.

[erorr_log7.txt](https://github.com/arayabrain/space-engineers-ai-spaceship-generator/files/9784765/erorr_log7.txt)

**Comment by gallorob** [comment]
Fixed in 81022302463286fc10f32abbef3a6ea2744e2669
