### ISSUE TITLE
.userstudyover -> reinitialize population call missing

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#65]
When I launch the application with .userstudyover file present, it loads a screen with no population - could you please make it initialize the population on launch? I thought this was a bug until I realized I had to click the "Reinitialize Population" button.

**Comment by gallorob** [comment]
@martinpoliak-goodai added in ccbd99140accc706764875cf353ac58d3332ba7d, 8be55eabf46468954a8895d6ef22b91b6d4adef3

This essentially emulates declining the privacy policy.
