### ISSUE TITLE
No solutions generated

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#69]
During the sync call, we saw 0 solutions being generated - can you please investigate?

**Comment by gallorob** [comment]
@martinpoliak-goodai , as discussed after the sync call, I've added in a0081d4fb4afaa77b946ade7983c993166e4ddc9 a simple slider that controls how many automated iterations are run:
![image](https://user-images.githubusercontent.com/32876132/198170088-4214677a-8e9a-4e09-97a5-948a693f754e.png)

There are other parameters that the user may be interested in playing with (such as the patience threshold, mutability rates etc...), which for now can be changed in the config file _before_ compiling the executable, and which _cannot_ be changed within the webapp itself. Perhaps this can be a future improvement/feature for the dev mode, once this first release is out?

I'm leaving this issue open for now, though it should always be possible to obtain _some_ spaceships at each iteration.

**Comment by martinpoliak-goodai** [comment]
I tested the slider and it works fine, thanks!
