### ISSUE TITLE
Number of blocks not matching the sum of armor + non-armor

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#70]
At least once, we saw the following in the user mode:
![obrazek](https://user-images.githubusercontent.com/14159877/197953602-34cc0084-5d50-4780-8c7a-ec3437ebad40.png)

**Comment by gallorob** [comment]
Will be fixed in the next commit

![image](https://user-images.githubusercontent.com/32876132/197967309-19d758dd-877e-45e7-9aa9-e0a646f7fce2.png)
