### ISSUE TITLE
Allow the user to enter "unsafe mode"

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#71]
Unsafe mode = allowing the user to generate ships without enough thrusters, as a tradeoff for allowing larger creativity of the evolution process. GUI: checkbox with a popup warning (because the population needs to be re-initialized).

**Comment by gallorob** [comment]
@martinpoliak-goodai tagging to make sure you will be notified of the changes--let me know if you run into any issues.

**Comment by martinpoliak-goodai** [comment]
Thanks Roberto for the change, this looks good, I would propose adjusting the text of the popup:
![obrazek](https://user-images.githubusercontent.com/14159877/198095961-5b184171-0d9d-44c0-9300-75d1b2c546c3.png)

**Comment by martinpoliak-goodai** [comment]
When toggling safe mode back on again, I got the same popup as before. There should be a different popup, because this time it will be turning the safe mode on. We should again be asking for a confirmation, because it the action will again reinitialize the population.

Suggested texts:
"Turn on safe mode?"

"Do you want to turn on safe mode again? This will reset the current progress of evolution, because the population of spaceships will need to be re-initialized."

[[[ Yes ]]]

**Comment by martinpoliak-goodai** [comment]
The "unsafe" mode seems to work fine 👍

**Comment by gallorob** [comment]
@martinpoliak-goodai I've updated the modal title and body message in 2265ddbd911e395b4290d24b9ba9fcf614861a3b following your suggestions.

Please double check if it's as you intended.
